[pytest]

addopts = -v -s

markers =
    comparison : Comparison Test
    generation : Benchmark Generation Test
    loadflow: Load flow tests
    fault_all: Fault analysis on all busbars
    fault_selected: Fault analysis on selected busbars
    loadflow_sheet : Load Flow analysis per sheet difference 
    fault_sheet : Fault Level analysis per sheet difference