[Benchmark]

# true -> generate benchmark
# false -> compare against benchmark
IsBenchmarkGeneration = true

# Version information
BASE_VERSION = vbenchmark
TEST_VERSION = v3.3.0

# Location of benchmark zip on network drive
NETWORK_BENCHMARK = S:\Adarsh\vbenchmark.zip